services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc:/var/jenkins_home/casc_configs
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home: