services:
  jenkins:
    build: .
    user: root
    ports:
      - "8083:8080"
      - "50003:50000"
    volumes:
      - ./jcasc:/var/jenkins_home/casc_configs
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml

volumes:
  jenkins_home: